In [1]:
import numpy as np



# CREATING ARRAY




In [2]:
array = np.array([1,2,3,4,5,6,7,8])
print(array)

[1 2 3 4 5 6 7 8]


# CREATING MATRIX

In [3]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# TRANSPOSING MATRIX

In [4]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# SQUARE OF NUMBERS

In [5]:
#underroot of 25
square = np.sqrt(25)
square

5.0

In [6]:
square1 = np.square(5)
square1

25

# ARRANGE NUMBERS

In [7]:
arrange = np.arange(1,100)
arrange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# LINESPACE

In [8]:
linespace = np.linspace(1,10,2)
linespace

array([ 1., 10.])

# RESHAPING

In [9]:
#we do reshping of arrays to shape it into matrix form
array.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# ZEROS

In [10]:
zeros = np.zeros([4,4])
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# ONES

In [11]:
ones = np.ones([4,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# IDENTITY MATRIX

In [12]:
ident = np.eye(5,4)
ident

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# UNIQUE

In [13]:
variable = np.array([1,2,3,4,3,2,1,4,"john","love","got","love","dare"])
variable

array(['1', '2', '3', '4', '3', '2', '1', '4', 'john', 'love', 'got',
       'love', 'dare'], dtype='<U11')

In [14]:
np.unique(variable)

array(['1', '2', '3', '4', 'dare', 'got', 'john', 'love'], dtype='<U11')

# Mathematical Operations of 2 Arrays


In [15]:
array2 = np.array([4,5,6,7,2,7,4,8])
array3 = array+array2
array3

array([ 5,  7,  9, 11,  7, 13, 11, 16])

In [16]:
array4 = array*array2
array4

array([ 4, 10, 18, 28, 10, 42, 28, 64])

In [17]:
array5 = array-array2
array5

array([-3, -3, -3, -3,  3, -1,  3,  0])

In [18]:
array6 = array/array2
array6

array([0.25      , 0.4       , 0.5       , 0.57142857, 2.5       ,
       0.85714286, 1.75      , 1.        ])

# RANDOM NUMBER

In [19]:
random = np.random.randn(4,3)
random

array([[ 0.91798848,  0.44081444,  2.39563779],
       [ 0.77793449,  0.62571248,  0.04019395],
       [-0.04507718,  0.44019506, -2.61366573],
       [-0.33310022,  1.05139803, -0.40851163]])

In [20]:
random1 = np.random.rand(4,3)
random1

array([[0.63834882, 0.52307769, 0.19841444],
       [0.99949905, 0.33817244, 0.09164267],
       [0.31023657, 0.2255899 , 0.53570882],
       [0.12925643, 0.59427823, 0.78230258]])

# RANDOM NUMBERS GENERATION AND SORTING

In [21]:
random_number = np.random.randint(10,20, size=10)
random_number

array([12, 10, 19, 16, 11, 18, 10, 15, 18, 17])

In [22]:
np.sort(random_number)

array([10, 10, 11, 12, 15, 16, 17, 18, 18, 19])

In [23]:
random>random1

array([[ True, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [24]:
np.max(random)

2.3956377866564806

In [25]:
np.min(random)

-2.61366573146032

In [26]:
random>random1

array([[ True, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [27]:
print(random[random>1])

[2.39563779 1.05139803]
